# Generated by Django 3.1.5 on 2021-01-17 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('creator', models.CharField(max_length=100)),
                ('assigned_to', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
                ('tags', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'task',
                'verbose_name_plural': 'tasks',
            },
        ),
    ]
