# Generated by Django 3.1.5 on 2021-01-26 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='assigned_to',
            new_name='executor',
        ),
        migrations.RenameField(
            model_name='tasks',
            old_name='labels',
            new_name='label',
        ),
        migrations.RemoveField(
            model_name='tasks',
            name='self_task',
        ),
    ]
